#!/bin/bash

echo "📋 CareOn 플랫폼 환경변수 설정 가이드"
echo "====================================="
echo ""
echo "1. .env.local 파일을 생성하세요:"
echo "   cp .env.local.example .env.local"
echo ""
echo "2. Supabase Dashboard에서 키를 가져오세요:"
echo "   - URL: https://supabase.com/dashboard/project/bvhfjfpsedkfqvmxwvfr"
echo "   - Settings > API 메뉴로 이동"
echo "   - anon key와 service_role key 복사"
echo ""
echo "3. .env.local 파일을 열어 키를 입력하세요:"
echo "   - NEXT_PUBLIC_SUPABASE_ANON_KEY=여기에_anon_key_입력"
echo "   - SUPABASE_SERVICE_ROLE_KEY=여기에_service_role_key_입력"
echo ""
echo "⚠️  주의사항:"
echo "   - Service Role Key는 절대 GitHub에 커밋하지 마세요!"
echo "   - .env.local 파일은 .gitignore에 포함되어 있습니다."
echo ""
echo "✅ 설정 완료 후 개발 서버를 다시 시작하세요:"
echo "   npm run dev"
